version: '3'

#  This application has web which is angular insdie Nginx
#  and API which used Redis inside
# 
# 

services:
  gateway:
    restart: always
    build: 
      context: ./gateway
    ports:
      - "3050:80"
  web:
    build:
      # dockerfile: .
      context: ./web
    volumes: 
      - /app/node_modules
      - ./web:/app

  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  redis:
    image: 'redis:latest'